version: '2.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: statuspage_mongo
    env:
      VIRTUAL_HOST: statuspage.agilepromoter.com
      VIRTUAL_PORT: 8080
      CERT_NAME: default

  statuspage:
    build: ./
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - MONGO_URI=mongo
